Repository vntchain/go-vnt, pull requests merged in 2019-04, with the labels that each got.

#62 修复向选举合约转账会使节点panic的bug
  core/vm/election/election.go
Labels: fix

#70 Fix bounty
  consensus/dpos/dpos.go
Labels: fix

#71 优化p2p日志打印
  vntp2p/discovery.go
  vntp2p/message.go
Labels: enhancement

#73 clean code of dpos module
  consensus/dpos/bft.go
  consensus/dpos/dpos.go
  consensus/dpos/msg_pool_test.go
  core/types/bft_msg.go
  core/vm/election/election.go
Labels: enhancement, fix

#74 clean code and fix tests of election
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb.go
  core/vm/election/electiondb_test.go
Labels: enhancement, fix
