Repository vntchain/go-vnt, pull requests merged in 2019-03, with the labels that each got.

#33 Bug fix
  internal/jsre/deps/bindata.go
  internal/jsre/deps/vnt.js
  internal/vntjsext/vntjsext.go
  vnt/filters/api.go
Labels: bug, fix

#34 Peers
  .travis.yml
  cmd/swarm/upload_test.go
  consensus/dpos/bft.go
  consensus/dpos/dpos.go
  core/blockchain.go
  core/genesis.go
  miner/worker.go
  params/config.go
  vnt/handler.go
  vnt/peer.go
  vntp2p/dial.go
  vntp2p/message.go
  vntp2p/peer.go
  vntp2p/server.go
Labels: bug, ci, fix

#43 Unit test
  .travis.yml
  accounts/abi/bind/backends/simulated.go
  consensus/dpos/dpos.go
  tests/block_test_util.go
  vnt/downloader/downloader_test.go
  vnt/fetcher/fetcher_test.go
  vnt/filters/filter_system_test.go
  vnt/filters/filter_test.go
Labels: ci, fix, tests

#44 Fix develop failed unit tests
  .travis.yml
  accounts/abi/bind/backends/simulated.go
  consensus/dpos/dpos.go
  tests/block_test_util.go
  vnt/downloader/downloader_test.go
  vnt/fetcher/fetcher_test.go
  vnt/filters/filter_system_test.go
  vnt/filters/filter_test.go
Labels: ci, fix, tests

#28 vntclient模块增加操作Vortex选举合约的接口
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb.go
  core/vm/election/electiondb_test.go
  internal/vntapi/api.go
  vntclient/vntclient.go
Labels: enhancement

#47 Fix reorg of choosing block
  core/blockchain.go
  core/blockchain_test.go
Labels: fix

#48 fix(election): any election contract need consume gas
  core/state_transition.go
Labels: fix

#59 fix(p2p): making p2p Node support toml
  vntp2p/node.go
  vntp2p/server.go
Labels: bug
