Repository vntchain/go-vnt, pull requests merged in 2019-06, with the labels that each got.

#92 fix some tests
  accounts/abi/bind/util_test.go
  cmd/gvnt/genesis_test.go
  vnt/backend.go
Labels: tests

#93 remove some issues not belong to go-vnt
  cmd/gvnt/accountcmd_test.go
  core/bloombits/matcher_test.go
  signer/core/validation.go
  swarm/api/http/roundtripper.go
  vntp2p/README.md
Labels: tests

#95 Refactor mined to produced
  .gitlab-ci.yml
  accounts/abi/bind/backend.go
  accounts/abi/bind/backends/simulated.go
  accounts/abi/bind/util.go
  accounts/abi/bind/util_test.go
  cmd/clef/4byte.json
  cmd/gvnt/main.go
  cmd/puppeth/module_node.go
  cmd/puppeth/wizard_intro.go
  cmd/puppeth/wizard_node.go
  consensus/consensus.go
  consensus/dpos/dpos.go
  containers/docker/vnt-ubuntu/run.sh
  core/block_validator.go
  core/blockchain_test.go
  core/chain_makers_test.go
  core/events.go
  core/tx_pool.go
  core/types/gen_header_json.go
  interfaces.go
  les/txrelay.go
  light/odr_test.go
  light/txpool.go
  light/txpool_test.go
  mobile/vntclient.go
  producer/agent.go
  producer/producer.go
  producer/remote_agent.go
  producer/unconfirmed.go
  producer/unconfirmed_test.go
  producer/worker.go
  signer/core/abihelper_test.go
  vnt/api.go
  vnt/api_backend.go
  vnt/api_tracer.go
  vnt/backend.go
  vnt/downloader/downloader.go
  vnt/downloader/downloader_test.go
  vnt/fetcher/fetcher_test.go
  vnt/filters/api.go
  vnt/filters/filter_system.go
  vnt/filters/filter_system_test.go
  vnt/gen_config.go
  vnt/handler.go
  vnt/tracers/tracers_test.go
  vntclient/vntclient.go
  vntp2p/README.md
  vntstats/vntstats.go
Labels: refactor

#96 Enhance p2p log, let it print peer id automatically
  vnt/handler.go
  vntp2p/message.go
  vntp2p/peer.go
  vntp2p/protocol.go
  vntp2p/server.go
Labels: enhancement

#98 remove eth
  .gitignore
  accounts/abi/bind/bind_test.go
  accounts/abi/bind/template.go
  accounts/keystore/keystore.go
  accounts/keystore/keystore_mobile.go
  accounts/keystore/keystore_plain_test.go
  accounts/keystore/keystore_secure_enclave.go
  accounts/keystore/presale.go
  build/ci.go
  build/env.sh
  build/nsis.gvnt.nsi
  build/nsis.uninstall.nsh
  cmd/faucet/faucet.go
  cmd/faucet/website.go
  cmd/gvnt/config.go
  cmd/gvnt/main.go
  cmd/gvnt/testdata/guswallet.json
  cmd/gvnt/usage.go
  cmd/puppeth/module_explorer.go
  cmd/puppeth/module_faucet.go
  cmd/puppeth/module_node.go
  cmd/puppeth/module_vntstats.go
  cmd/puppeth/module_wallet.go
  cmd/puppeth/wizard.go
  cmd/puppeth/wizard_faucet.go
  cmd/puppeth/wizard_intro.go
  cmd/puppeth/wizard_netstats.go
  cmd/puppeth/wizard_network.go
  cmd/puppeth/wizard_node.go
  cmd/puppeth/wizard_vntstats.go
  cmd/puppeth/wizard_wallet.go
  cmd/utils/flags.go
  cmd/vntkey/utils.go
  console/console_test.go
  core/genesis.go
  core/helper_test.go
  internal/vntapi/api.go
  les/backend.go
  light/postprocess.go
  mobile/gvnt.go
  node/config.go
  rpc/client.go
  rpc/client_example_test.go
  rpc/server.go
  rpc/subscription_test.go
  signer/core/api.go
  swarm/api/api_test.go
  swarm/dev/scripts/boot-cluster.sh
  vnt/api.go
  vnt/filters/api.go
  vntp2p/protocol.go
  vntstats/vntstats.go
Labels: refactor

#99 Clean useless vendor
  vendor/github.com/ethereum/ethash/src/libethash/CMakeLists.txt
  vendor/github.com/ethereum/ethash/src/libethash/compiler.h
  vendor/github.com/ethereum/ethash/src/libethash/data_sizes.h
  vendor/github.com/ethereum/ethash/src/libethash/endian.h
  vendor/github.com/ethereum/ethash/src/libethash/ethash.h
  vendor/github.com/ethereum/ethash/src/libethash/fnv.h
  vendor/github.com/ethereum/ethash/src/libethash/internal.c
  vendor/github.com/ethereum/ethash/src/libethash/internal.h
  vendor/github.com/ethereum/ethash/src/libethash/io.c
  vendor/github.com/ethereum/ethash/src/libethash/io.h
  vendor/github.com/ethereum/ethash/src/libethash/io_posix.c
  vendor/github.com/ethereum/ethash/src/libethash/io_win32.c
  vendor/github.com/ethereum/ethash/src/libethash/mmap.h
  vendor/github.com/ethereum/ethash/src/libethash/mmap_win32.c
  vendor/github.com/ethereum/ethash/src/libethash/sha3.c
  vendor/github.com/ethereum/ethash/src/libethash/sha3.h
  vendor/github.com/ethereum/ethash/src/libethash/sha3_cryptopp.cpp
  vendor/github.com/ethereum/ethash/src/libethash/sha3_cryptopp.h
  vendor/github.com/ethereum/ethash/src/libethash/util.h
  vendor/github.com/ethereum/ethash/src/libethash/util_win32.c
Labels: refactor

#103 Flush trie cache db once an hour to fix sync block from 0
  core/blockchain.go
  vnt/config.go
Labels: fix

#101 Remove the dependence of agent for producer
  producer/agent.go
  producer/producer.go
  producer/remote_agent.go
  producer/worker.go
  vnt/api.go
Labels: refactor

#104 Using transafer VNT for election stake
  core/chain_makers_test.go
  core/vm/contracts.go
  core/vm/election/abi.go
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb_test.go
  core/vm/election/mainnet.go
  internal/vntapi/api.go
  rpc/types.go
  vntclient/vntclient.go
Labels: enhancement
