Repository vntchain/go-vnt, pull requests merged in 2019-01, with the labels that each got.

#3 配置Travis CI
  .github/ISSUE_TEMPLATE/bug_report.md
  .travis.yml
Labels: ci

#7 feature: 修改bft quorum阈值
  consensus/dpos/bft.go
  consensus/dpos/msg_pool_test.go
Labels: fix

#8 合入见证人和bft修改
  .github/ISSUE_TEMPLATE/bug_report.md
  .travis.yml
  consensus/dpos/bft.go
  consensus/dpos/dpos.go
  consensus/dpos/msg_pool_test.go
  core/types/block.go
  core/types/gen_header_json.go
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb.go
  core/vm/election/electiondb_test.go
  internal/vntapi/api.go
  rpc/types.go
Labels: enhancement, fix

#12 fix：修复投票合约相关问题
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb.go
  internal/vntapi/api.go
  rpc/types.go
  vnt/handler.go
Labels: enhancement, fix

#14 修复core的test文件和dpos模块循环引用的问题，修复core和light以及console的单元测试
  .gitlab-ci.yml
  .travis.yml
  consensus/dpos/manager.go
  consensus/mock/mock.go
  console/console_test.go
  core/bench_test.go
  core/block_validator_test.go
  core/blockchain_test.go
  core/chain_makers_test.go
  core/database_util.go
  core/genesis_test.go
  light/lightchain_test.go
  light/odr_test.go
  light/trie_test.go
  light/txpool_test.go
  params/config.go
  params/protocol_params.go
Labels: fix

#15 增加见证人单元测试
  core/vm/election/election.go
  core/vm/election/election_test.go
  vnt/fetcher/fetcher.go
  vnt/handler.go
Labels: tests

#16 修复core的test文件和dpos模块循环引用的问题，修复core和light以及console的单元测试
  .gitlab-ci.yml
  .travis.yml
  consensus/dpos/manager.go
  consensus/mock/mock.go
  console/console_test.go
  core/bench_test.go
  core/block_validator_test.go
  core/blockchain_test.go
  core/chain_makers_test.go
  core/database_util.go
  core/genesis_test.go
  light/lightchain_test.go
  light/odr_test.go
  light/trie_test.go
  light/txpool_test.go
  params/config.go
  params/protocol_params.go
Labels: ci, tests
