Repository vntchain/go-vnt, pull requests merged in 2019-05, with the labels that each got.

#75 Unstoppable
  node/node.go
  vntp2p/message.go
  vntp2p/peer.go
  vntp2p/server.go
Labels: bug

#76 remove unused ticker and variable
  vnt/handler.go
Labels: refactor

#78 Fix p2p mem leak
  vnt/peer.go
  vntp2p/dial.go
  vntp2p/message.go
  vntp2p/peer.go
  vntp2p/protocol.go
  vntp2p/server.go
  whisper/whisperv6/peer.go
  whisper/whisperv6/whisper.go
Labels: fix

#79 fix some typo and misname
  vntp2p/dial.go
  vntp2p/message.go
  vntp2p/peer.go
  vntp2p/protocol.go
  vntp2p/server.go
Labels: fix

#80 Remove some unused errors
  vnt/backend.go
  vntp2p/dial.go
  vntp2p/message.go
  vntp2p/protocol.go
  vntp2p/server.go
Labels: fix

#83 Clean the code of vntp2p
  core/tx_pool_test.go
  crypto/bn256/google/main_test.go
  vntp2p/database.go
  vntp2p/dial.go
  vntp2p/message.go
  vntp2p/netutil/error_test.go
  vntp2p/netutil/net_test.go
  vntp2p/peer.go
  vntp2p/protocol.go
  vntp2p/server.go
Labels: fix

#87 Quick LIB to finalize block
  core/blockchain.go
  core/blockchain_test.go
  core/chain_makers.go
  core/error.go
  core/headerchain.go
  light/lightchain_test.go
  miner/worker.go
Labels: enhancement

#90 update vnt.js
  internal/jsre/deps/bindata.go
  internal/jsre/deps/vnt.js
Labels: fix

#91 Support main net active
  core/blockchain_test.go
  core/chain_makers.go
  core/mainnet_test.go
  core/vm/election/abi.go
  core/vm/election/election.go
  core/vm/election/election_test.go
  core/vm/election/electiondb.go
  core/vm/election/electiondb_test.go
  core/vm/election/mainnet.go
  core/wavm/wavm.go
  internal/vntapi/api.go
  light/odr_test.go
  rpc/types.go
  vntclient/vntclient.go
Labels: enhancement
